# render.yaml
services:
  - type: web
    name: report-rocket
    env: python
    region: oregon         # match the region you chose for Postgres
    plan: starter          # free works for testing, starter is recommended
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false        # set this in Render dashboard (Environment tab)
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL   # this will be filled automatically by the DB block below
        fromDatabase:
          name: report-rocket-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

    # Create tables after each successful deploy
    postDeployCommand: >
      python -c "from app import app; from models import db; 
      import os; 
      with app.app_context(): 
          db.create_all(); 
          print('✅ DB tables ensured')"

databases:
  - name: report-rocket-db
    databaseName: report_rocket    # optional; Render will generate one if omitted
    region: oregon
    plan: starter
