services:
  - type: web
    name: report-rocket-web
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    healthCheckPath: /
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION         # Pin Python so deps stay stable
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY         # set in Render Dashboard
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: report-rocket-db
          property: connectionString

    # Persist CSV exports between deploys/restarts
    disk:
      name: exports
      mountPath: /opt/render/project/src/exports
      sizeGB: 1

    # Create tables on first deploys (idempotent)
    postDeployCommand: >
      python -c "from app import app, db; from models import *;
      app.app_context().push(); db.create_all(); print('DB tables created')"

databases:
  - name: report-rocket-db
    plan: starter
