"""init schema

Revision ID: 6e816df778ae
Revises: 
Create Date: 2025-09-07 11:39:21.030160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e816df778ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reports_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reports_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reports_limit')
        batch_op.drop_column('reports_used')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
